/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/url-encode-decode";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("url-encode-decode");
}

export default function Page() {
  return <ToolStaticPage slug="url-encode-decode" toolClient={<ToolClient />} />;
}
