/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/pdf-text-extractor";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("pdf-text-extractor");
}

export default function Page() {
  return <ToolStaticPage slug="pdf-text-extractor" toolClient={<ToolClient />} />;
}
