/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/safe-days-calculator";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("safe-days-calculator");
}

export default function Page() {
  return <ToolStaticPage slug="safe-days-calculator" toolClient={<ToolClient />} />;
}
