/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/date-difference-calculator";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("date-difference-calculator");
}

export default function Page() {
  return <ToolStaticPage slug="date-difference-calculator" toolClient={<ToolClient />} />;
}
