/* AUTO-GENERATED by scripts/generate-premium-batches.mjs — curated-style quotes per tool */
export type ToolTestimonial = {
  name: string;
  rating: number;
  text: string;
  title?: string;
};

export const toolTestimonials: Record<string, ToolTestimonial[]> = {
  "/word-counter": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Word Counter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Word Counter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Word Counter saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/text-case-converter": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Text Case Converter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Text Case Converter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Text Case Converter saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/text-font-changer": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Text Font Changer. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Text Font Changer saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/ai-text-rewriter": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "AI Text Rewriter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ AI Text Rewriter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. AI Text Rewriter saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/lorem-ipsum-generator": [
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Lorem Ipsum Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Lorem Ipsum Generator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/whitespace-remover": [
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Whitespace Remover is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Whitespace Remover. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/duplicate-line-remover": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Duplicate Line Remover saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Duplicate Line Remover is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/text-reverser": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Text Reverser. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Text Reverser saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/regex-tester": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Regex Tester is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Regex Tester. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Regex Tester saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/base64-converter": [
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Base64 Converter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Base64 Converter saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/text-to-handwriting": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Text to Handwriting is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Text to Handwriting. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Text to Handwriting saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/url-slug-generator": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. URL Slug Generator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "URL Slug Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/notes": [
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Notes saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Notes is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/timestamp-converter": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Timestamp Converter saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the converter tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Timestamp Converter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/image-compressor": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Image Compressor saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Image Compressor is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/logo-to-favicon": [
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Logo to Favicon Converter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Logo to Favicon Converter. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/image-upscaler": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Image Upscaler is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Image Upscaler. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Image Upscaler saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/image-cropper": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Image Cropper & Resizer is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Image Cropper & Resizer. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Image Cropper & Resizer saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/image-format-converter": [
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Image Format Converter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Image Format Converter saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/svg-optimizer": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ SVG Optimizer. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. SVG Optimizer saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/image-metadata-viewer": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Image Metadata Viewer. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Image Metadata Viewer saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/image-to-text": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Image to Text saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Image to Text is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/pdf-text-extractor": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. PDF Text Extractor saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "PDF Text Extractor is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/placeholder-image-generator": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Placeholder Image Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Placeholder Image Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Placeholder Image Generator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/pixelate-tool": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Pixelate Tool saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Pixelate Tool is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/photo-annotation-tool": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Photo Annotation Tool is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Photo Annotation Tool. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Photo Annotation Tool saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/background-remover": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Background Remover saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Background Remover is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/merge-images": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Merge Images is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Merge Images. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Merge Images saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/flip-image": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Flip Image saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Flip Image is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/blur-image": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Blur Image is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Blur Image. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Blur Image saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/split-image": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Split Image is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Split Image. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/invert-image-colors": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Invert Image Colors saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Invert Image Colors is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/image-resizer": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Image Resizer. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Image Resizer saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/add-name-date-photo": [
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Add Name & Date on Photo saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Add Name & Date on Photo is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/qr-scanner": [
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the image tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "QR Scanner is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ QR Scanner. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/typing-tutor": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Typing Tutor. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Typing Tutor saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the typing tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/typing-test": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Typing Test. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Typing Test saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the typing tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/typing-games": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Typing Games saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the typing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Typing Games is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/typing-competition": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Typing Competition is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Typing Competition. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Typing Competition saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/qr-code-generator": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "QR Code Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ QR Code Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. QR Code Generator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/password-generator": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Password Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Password Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Password Generator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/json-formatter": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "JSON Beautifier & Formatter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ JSON Beautifier & Formatter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. JSON Beautifier & Formatter saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/color-picker-tool": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Color Picker saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Color Picker is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/todo-list": [
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. To-Do List saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "To-Do List is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/daily-task-report-saver": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Daily Task Report Saver. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Daily Task Report Saver saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/timetable-maker": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Timetable Maker. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Timetable Maker saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/list-randomizer": [
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "List Randomizer is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ List Randomizer. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/barcode-generator": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Barcode Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Barcode Generator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/barcode-scanner-online": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Barcode Scanner saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Barcode Scanner is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/simple-calculator": [
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Simple Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Simple Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/age-calculator": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Age Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Age Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/date-difference-calculator": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Date Difference Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Date Difference Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/future-date-calculator": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Future Date Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Future Date Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/bmi-calculator": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "BMI Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ BMI Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. BMI Calculator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/percentage-calculator": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Percentage Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Percentage Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/currency-converter": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Currency Converter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Currency Converter saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/gst-calculator": [
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. GST Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "GST Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/emi-calculator": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ EMI Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. EMI Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/sip-calculator": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "SIP & Lumpsum Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ SIP & Lumpsum Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. SIP & Lumpsum Calculator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/ppf-calculator": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "PPF Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ PPF Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. PPF Calculator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/fd-calculator": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. FD Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "FD Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/income-tax-calculator": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the number tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Income Tax Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Income Tax Calculator. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/period-calculator": [
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the period & cycle tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Period Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Period Calculator. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/ovulation-calculator": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Ovulation Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Ovulation Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the period & cycle tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/safe-days-calculator": [
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Safe Days Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Safe Days Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the period & cycle tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/period-tracker": [
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Period Tracker. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Period Tracker saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the period & cycle tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/pms-symptom-tracker": [
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. PMS Symptom Tracker saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the period & cycle tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "PMS Symptom Tracker is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/pregnancy-due-date-calculator": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Pregnancy Due Date Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Pregnancy Due Date Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the pregnancy tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/pregnancy-week-calculator": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Pregnancy Week Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Pregnancy Week Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Pregnancy Week Calculator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/conception-date-calculator": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Conception Date Calculator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Conception Date Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the pregnancy tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/pregnancy-weight-gain-calculator": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Pregnancy Weight Gain Calculator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the pregnancy tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Pregnancy Weight Gain Calculator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/contraction-timer": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the pregnancy tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Contraction Timer is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Contraction Timer. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/baby-kick-counter": [
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the pregnancy tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Baby Kick Counter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Baby Kick Counter. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/pregnancy-diet-planner": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Pregnancy Diet Planner is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Pregnancy Diet Planner. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Pregnancy Diet Planner saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/temperature-converter": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Temperature Converter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Temperature Converter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Temperature Converter saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/unit-converter": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Unit Converter saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the converter tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Unit Converter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/enhanced-unit-converter": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Enhanced Unit Converter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Enhanced Unit Converter saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the converter tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/hash-generator": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Hash Generator & Comparator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Hash Generator & Comparator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/jwt-decoder": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "JWT Token Decoder is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ JWT Token Decoder. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/meta-tag-previewer": [
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Meta Tag Previewer is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Meta Tag Previewer. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/live-preview": [
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Live HTML Previewer saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Live HTML Previewer is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/javascript-minifier": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "JavaScript Minifier is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ JavaScript Minifier. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. JavaScript Minifier saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/table-to-json-converter": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Table to JSON Converter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Table to JSON Converter. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/xml-sitemap-tester": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "XML Sitemap Tester & Validator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ XML Sitemap Tester & Validator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. XML Sitemap Tester & Validator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/trip-expense-splitter": [
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Trip Expense Splitter & Manager. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Trip Expense Splitter & Manager saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the finance tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/stopwatch": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Stopwatch saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the timer tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Stopwatch is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/countdown-timer": [
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Countdown Timer saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the timer tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Countdown Timer is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/ip-lookup": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ What. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. What saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the network tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/ip-address-to-location-finder": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "IP Address to Location Finder is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ IP Address to Location Finder. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. IP Address to Location Finder saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/social-media-db-viewer": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the video & social media tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Social Media DB Viewer is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Social Media DB Viewer. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/social-media-downloader": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Instagram & Facebook Downloader. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Instagram & Facebook Downloader saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the video & social media tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/box-shadow-generator": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Box Shadow Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Box Shadow Generator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/border-radius-generator": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Border Radius Generator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Border Radius Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/button-generator": [
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Button Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Button Generator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/css-minifier": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "CSS Minifier is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ CSS Minifier. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. CSS Minifier saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/gradient-generator": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Gradient Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Gradient Generator. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/html-formatter": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ HTML Formatter. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. HTML Formatter saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the development tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/json-validator": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "JSON Validator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ JSON Validator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. JSON Validator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/url-encode-decode": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "URL Encode Decode is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ URL Encode Decode. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. URL Encode Decode saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/coin-flip": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Coin Flip saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Coin Flip is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/dice-roller": [
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Dice Roller. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Dice Roller saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/random-number-generator": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Random Number Generator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Random Number Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/url-shortener": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ URL Shortener. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. URL Shortener saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the utility tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/yes-no-generator": [
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Yes/No Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Yes/No Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Yes/No Generator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/business-idea-generator": [
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Business Idea Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Business Idea Generator. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/discord-formatter": [
    {
      "name": "Amelia Wright",
      "title": "Social Media Manager",
      "text": "Clear outputs and mobile-friendly controls. Discord Formatter saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Discord Formatter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    }
  ],
  "/hashtag-generator": [
    {
      "name": "Marcus Cole",
      "title": "Growth Lead",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Hashtag Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Hashtag Generator. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/markdown-editor": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Markdown Editor is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Markdown Editor. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Markdown Editor saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/name-generator": [
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Name Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Name Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Priya Sharma",
      "title": "Product Designer",
      "text": "Clear outputs and mobile-friendly controls. Name Generator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/username-generator": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the text & writing tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Username Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Username Generator. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/color-converter": [
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the converter tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Elena Rossi",
      "title": "Graduate Student",
      "text": "Color Converter is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Kenji Sato",
      "title": "Data Analyst",
      "text": "I switched from a cluttered extension to FYN Tools’ Color Converter. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/color-palette-generator": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Color Palette Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Color Palette Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Color Palette Generator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/social-media-deep-link-generator": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Social Media Deep Link Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Social Media Deep Link Generator saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the video & social media tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/social-media-planner": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Social Media Planner is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Social Media Planner. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Social Media Planner saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/text-to-speech": [
    {
      "name": "Dev Patel",
      "title": "Full-Stack Engineer",
      "text": "Exactly the video & social media tools utility I needed without installing desktop software.",
      "rating": 5
    },
    {
      "name": "Aisha Khan",
      "title": "Content Marketer",
      "text": "Text to Speech is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Noah Park",
      "title": "Freelance Writer",
      "text": "I switched from a cluttered extension to FYN Tools’ Text to Speech. No signup friction for quick jobs.",
      "rating": 5
    }
  ],
  "/weather-forecast": [
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Weather Forecast. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Weather Forecast saves me a few minutes every week.",
      "rating": 4
    },
    {
      "name": "Omar Hassan",
      "title": "Finance Analyst",
      "text": "Exactly the network tools utility I needed without installing desktop software.",
      "rating": 5
    }
  ],
  "/invoice-generator": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Invoice Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Invoice Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Invoice Generator saves me a few minutes every week.",
      "rating": 4
    }
  ],
  "/dummy-api-generator": [
    {
      "name": "Hannah Brooks",
      "title": "Operations Manager",
      "text": "Dummy API Generator is bookmarked on my work laptop — results are instant and the UI stays out of the way.",
      "rating": 4
    },
    {
      "name": "Jordan Lee",
      "title": "Frontend Developer",
      "text": "I switched from a cluttered extension to FYN Tools’ Dummy API Generator. No signup friction for quick jobs.",
      "rating": 5
    },
    {
      "name": "Sofia Mendes",
      "title": "SEO Specialist",
      "text": "Clear outputs and mobile-friendly controls. Dummy API Generator saves me a few minutes every week.",
      "rating": 4
    }
  ]
};
