/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/period-tracker";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("period-tracker");
}

export default function Page() {
  return <ToolStaticPage slug="period-tracker" toolClient={<ToolClient />} />;
}
