/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/barcode-scanner-online";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("barcode-scanner-online");
}

export default function Page() {
  return <ToolStaticPage slug="barcode-scanner-online" toolClient={<ToolClient />} />;
}
