/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/discord-formatter";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("discord-formatter");
}

export default function Page() {
  return <ToolStaticPage slug="discord-formatter" toolClient={<ToolClient />} />;
}
