/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/color-picker-tool";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("color-picker-tool");
}

export default function Page() {
  return <ToolStaticPage slug="color-picker-tool" toolClient={<ToolClient />} />;
}
