/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/qr-scanner";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("qr-scanner");
}

export default function Page() {
  return <ToolStaticPage slug="qr-scanner" toolClient={<ToolClient />} />;
}
