/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/bmi-calculator";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("bmi-calculator");
}

export default function Page() {
  return <ToolStaticPage slug="bmi-calculator" toolClient={<ToolClient />} />;
}
