/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/baby-kick-counter";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("baby-kick-counter");
}

export default function Page() {
  return <ToolStaticPage slug="baby-kick-counter" toolClient={<ToolClient />} />;
}
