/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/split-image";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("split-image");
}

export default function Page() {
  return <ToolStaticPage slug="split-image" toolClient={<ToolClient />} />;
}
