/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
export const NO_SSR_TOOL_SLUGS = new Set(["add-name-date-photo","background-remover","barcode-generator","barcode-scanner-online","blur-image","color-picker-tool","enhanced-unit-converter","flip-image","image-compressor","image-cropper","image-format-converter","image-metadata-viewer","image-resizer","image-to-text","image-upscaler","invert-image-colors","invoice-generator","ip-address-to-location-finder","logo-to-favicon","merge-images","pdf-text-extractor","photo-annotation-tool","pixelate-tool","placeholder-image-generator","pregnancy-diet-planner","qr-scanner","social-media-db-viewer","social-media-downloader","split-image","text-font-changer","text-to-handwriting","trip-expense-splitter","typing-competition","typing-games","typing-test","typing-tutor","weather-forecast"]);

export function toolNeedsClientOnly(slug: string): boolean {
  return NO_SSR_TOOL_SLUGS.has(slug);
}
