/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/photo-annotation-tool";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("photo-annotation-tool");
}

export default function Page() {
  return <ToolStaticPage slug="photo-annotation-tool" toolClient={<ToolClient />} />;
}
