/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/trip-expense-splitter";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("trip-expense-splitter");
}

export default function Page() {
  return <ToolStaticPage slug="trip-expense-splitter" toolClient={<ToolClient />} />;
}
