/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/social-media-db-viewer";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("social-media-db-viewer");
}

export default function Page() {
  return <ToolStaticPage slug="social-media-db-viewer" toolClient={<ToolClient />} />;
}
