/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/meta-tag-previewer";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("meta-tag-previewer");
}

export default function Page() {
  return <ToolStaticPage slug="meta-tag-previewer" toolClient={<ToolClient />} />;
}
