/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/jwt-decoder";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("jwt-decoder");
}

export default function Page() {
  return <ToolStaticPage slug="jwt-decoder" toolClient={<ToolClient />} />;
}
