/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/ai-text-rewriter";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("ai-text-rewriter");
}

export default function Page() {
  return <ToolStaticPage slug="ai-text-rewriter" toolClient={<ToolClient />} />;
}
