/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/live-preview";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("live-preview");
}

export default function Page() {
  return <ToolStaticPage slug="live-preview" toolClient={<ToolClient />} />;
}
