/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/pregnancy-diet-planner";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("pregnancy-diet-planner");
}

export default function Page() {
  return <ToolStaticPage slug="pregnancy-diet-planner" toolClient={<ToolClient />} />;
}
