'use client';
/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */

import dynamic from "next/dynamic";

const Tool = dynamic(() => import("@/components/tools/MergeImages"), {
  ssr: false,
});

/** Client-only island — see ToolCrawlerFallback for crawler-visible HTML. */
export default function ToolClient() {
  return (
    <div className="w-full min-h-[560px]" id="tool-interface">
      <Tool />
    </div>
  );
}
