'use client';
/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */

import dynamic from "next/dynamic";

const Tool = dynamic(() => import("@/components/tools/PlaceholderImageGenerator"), {
  ssr: false,
  loading: () => (
    <div
      className="w-full min-h-[560px] rounded-xl border border-zinc-200 dark:border-zinc-800 bg-muted/30 animate-pulse flex items-center justify-center text-muted-foreground"
      aria-busy="true"
      aria-label="Loading Placeholder Image Generator"
      role="status"
    >
      Loading tool…
    </div>
  ),
});

/** Dedicated island — only loads PlaceholderImageGenerator, not the multi-tool registry. */
export default function ToolClient() {
  return (
    <div className="w-full min-h-[560px]" id="tool-interface">
      <Tool />
    </div>
  );
}
