'use client';
/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */

import SimpleCalculator from "@/components/tools/SimpleCalculator";

/** Direct import — full HTML in SSR for Google/crawlers. */
export default function ToolClient() {
  return (
    <div className="w-full min-h-[420px]" id="tool-interface">
      <SimpleCalculator />
    </div>
  );
}
