'use client';
/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */

import SocialMediaPlanner from "@/components/tools/SocialMediaPlanner";

/** Direct import — full HTML in SSR for Google/crawlers. */
export default function ToolClient() {
  return (
    <div className="w-full min-h-[420px]" id="tool-interface">
      <SocialMediaPlanner />
    </div>
  );
}
