'use client';
/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */

import dynamic from "next/dynamic";

const Tool = dynamic(() => import("@/components/tools/SocialMediaLinkGenerator"), {
  ssr: true
});

/** Dedicated island — only loads SocialMediaLinkGenerator, not the multi-tool registry. */
export default function ToolClient() {
  return (
    <div className="w-full min-h-[420px]" id="tool-interface">
      <Tool />
    </div>
  );
}
