'use client';
/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */

import TimestampConverter from "@/components/tools/TimestampConverter";

/** Direct import — full HTML in SSR for Google/crawlers. */
export default function ToolClient() {
  return (
    <div className="w-full min-h-[420px]" id="tool-interface">
      <TimestampConverter />
    </div>
  );
}
