'use client';
/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */

import dynamic from "next/dynamic";

const Tool = dynamic(() => import("@/components/tools/WhitespaceRemover"), {
  ssr: false,
});

/** Client-only island — crawlable HTML is in ToolCrawlerFallback (server). */
export default function ToolClient() {
  return (
    <div className="w-full min-h-[560px]" id="tool-interface">
      <Tool />
    </div>
  );
}
