/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/ip-lookup";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("ip-lookup");
}

export default function Page() {
  return <ToolStaticPage slug="ip-lookup" toolClient={<ToolClient />} />;
}
