/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/duplicate-line-remover";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("duplicate-line-remover");
}

export default function Page() {
  return <ToolStaticPage slug="duplicate-line-remover" toolClient={<ToolClient />} />;
}
