/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/daily-task-report-saver";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("daily-task-report-saver");
}

export default function Page() {
  return <ToolStaticPage slug="daily-task-report-saver" toolClient={<ToolClient />} />;
}
