/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/contraction-timer";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("contraction-timer");
}

export default function Page() {
  return <ToolStaticPage slug="contraction-timer" toolClient={<ToolClient />} />;
}
