/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/regex-tester";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("regex-tester");
}

export default function Page() {
  return <ToolStaticPage slug="regex-tester" toolClient={<ToolClient />} />;
}
