/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/text-case-converter";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("text-case-converter");
}

export default function Page() {
  return <ToolStaticPage slug="text-case-converter" toolClient={<ToolClient />} />;
}
