/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/border-radius-generator";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("border-radius-generator");
}

export default function Page() {
  return <ToolStaticPage slug="border-radius-generator" toolClient={<ToolClient />} />;
}
