/* AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit */
import type { Metadata } from "next";
import ToolStaticPage, { buildToolPageMetadata } from "@/lib/tools/toolStaticPage";
import ToolClient from "@/lib/tools/clients/pms-symptom-tracker";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return buildToolPageMetadata("pms-symptom-tracker");
}

export default function Page() {
  return <ToolStaticPage slug="pms-symptom-tracker" toolClient={<ToolClient />} />;
}
